### ISSUE TITLE
Fresh ActivitySim install cannot run example_mtc_full in multiprocessing mode

### ISSUE THREAD

**Issue by mattwigway** [ActivitySim/activitysim#380]
I installed the ActivitySim `master` branch using `python setup.py develop`, then ran `activitysim create -e example_mtc_full -d example_mtc_full/` and `activitysim run -mw example_mtc_full/example_mtc_full`, and I get this traceback. The model runs without the `-m` flag. I'm using anaconda python 3.8.2 on OS X 11.2.1.

<details>
<summary>Traceback</summary>
```
############ mp_tasks - mp_initialize - mp_run_simulation mp_initialize
mp_initialize WARNING - activitysim.core.mp_tasks - KeyError exception running initialize_landuse model: 'no step named initialize_landuse'
mp_initialize ERROR - activitysim.core.mp_tasks - mp_tasks - mp_initialize - KeyError exception caught in mp_run_simulation: 'no step named initialize_landuse'
mp_initialize ERROR - activitysim.core.mp_tasks -
---
Traceback (most recent call last):
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 833, in mp_run_simulation
    run_simulation(queue, step_info, resume_after, shared_data_buffer)
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 791, in run_simulation
    raise e
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 788, in run_simulation
    pipeline.run_model(model)
  File "/Users/matthewc/git/activitysim/activitysim/core/pipeline.py", line 468, in run_model
    orca.run([step_name])
  File "/Users/matthewc/git/activitysim/activitysim/core/orca.py", line 2004, in run
    step_tables = get_step_table_names(steps)
  File "/Users/matthewc/git/activitysim/activitysim/core/orca.py", line 1907, in get_step_table_names
    table_names |= get_step(s)._tables_used()
  File "/Users/matthewc/git/activitysim/activitysim/core/orca.py", line 1593, in get_step
    raise KeyError('no step named {}'.format(step_name))
KeyError: 'no step named initialize_landuse'
---

Process mp_initialize:
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/asim/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/Caskroom/miniconda/base/envs/asim/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 840, in mp_run_simulation
    raise e
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 833, in mp_run_simulation
    run_simulation(queue, step_info, resume_after, shared_data_buffer)
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 791, in run_simulation
    raise e
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 788, in run_simulation
    pipeline.run_model(model)
  File "/Users/matthewc/git/activitysim/activitysim/core/pipeline.py", line 468, in run_model
    orca.run([step_name])
  File "/Users/matthewc/git/activitysim/activitysim/core/orca.py", line 2004, in run
    step_tables = get_step_table_names(steps)
  File "/Users/matthewc/git/activitysim/activitysim/core/orca.py", line 1907, in get_step_table_names
    table_names |= get_step(s)._tables_used()
  File "/Users/matthewc/git/activitysim/activitysim/core/orca.py", line 1593, in get_step
    raise KeyError('no step named {}'.format(step_name))
KeyError: 'no step named initialize_landuse'
Closing remaining open files:output/pipeline.h5...done
WARNING - activitysim.core.mp_tasks - process mp_initialize failed with exitcode 1
INFO - activitysim.core.mem - trace_memory_info mp_initialize.failed rss: 3.99GB used: 9.01 GB percent: 62.3%
WARNING - activitysim.core.mp_tasks - fail_fast terminating remaining running processes
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/asim/bin/activitysim", line 33, in <module>
    sys.exit(load_entry_point('activitysim', 'console_scripts', 'activitysim')())
  File "/Users/matthewc/git/activitysim/activitysim/cli/main.py", line 21, in main
    sys.exit(asim.execute())
  File "/Users/matthewc/git/activitysim/activitysim/cli/cli.py", line 27, in execute
    args.func(args)
  File "/Users/matthewc/git/activitysim/activitysim/cli/run.py", line 204, in run
    mp_tasks.run_multiprocess(run_list, injectables)
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 1321, in run_multiprocess
    completed = run_sub_simulations(injectables,
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 1143, in run_sub_simulations
    idle(seconds=1)
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 1058, in idle
    check_proc_status()
  File "/Users/matthewc/git/activitysim/activitysim/core/mp_tasks.py", line 1046, in check_proc_status
    raise RuntimeError("Process %s failed" % (p.name,))
RuntimeError: Process mp_initialize failed
```
</details>

**Comment by bstabler** [comment]
Hi @mattwigway, here's a quick update on this.   I ran example_mtc_full on my Windows server using the example commands in the [example_manifest.yaml](https://github.com/ActivitySim/activitysim/blob/master/activitysim/examples/example_manifest.yaml#L25).   This is using different command line arguments than "-mw", so we'll need to further investigate this configuration option.

**Comment by toliwaga** [comment]
Hi @mattwigway

I am not able to reproduce this. If you still believe you have an issue, please provide some more detail.

The fact that you are seeing this:

`KeyError: 'no step named initialize_landuse'`

Suggests that the following import (which has the side effect of registering the abm model stsp injectables) is not getting called:

`from activitysim import abm  # register injectables`

I did fix a bug related to that in the develop branch recently, but I was not aware of it in master, and have not seen it myself. So if you can reproduce it, let me know and I will try to reproduce it on my end.
