### ISSUE TITLE
Example test_example_mtc failed with asim 1.0.1

### ISSUE THREAD

**Issue by stevenhz** [ActivitySim/activitysim#464]
Dear,

I have followed the installation instructions and try to run the example MTC.  I see the installed version is 1.0.1.  The example fails in school-location model. Here below you can see the output. Could you see where it goes wrong? Thanks.

`activitysim create -e example_mtc -d test_example_mtc`
```
copying data ...
copying configs ...
copying configs_mp ...
copying output ...
copying README.MD ...
copied! new project files are in L:\UserData\Han\activitysimtno\test_example_mtc
```
Inside test_example_mtc folder, type `activitysim run -c configs -o output -d data`
```
Configured logging using basicConfig
INFO:activitysim:Configured logging using basicConfig
INFO - Read logging configuration from: configs\logging.yaml
INFO - SETTING configs_dir: ['configs']
INFO - SETTING settings_file_name: settings.yaml
INFO - SETTING data_dir: ['data']
INFO - SETTING output_dir: output
INFO - SETTING households_sample_size: 100
INFO - SETTING chunk_size: 0
INFO - SETTING chunk_method: hybrid_uss
INFO - SETTING chunk_training_mode: training
INFO - SETTING multiprocess: None
INFO - SETTING num_processes: None
INFO - SETTING resume_after: None
INFO - SETTING trace_hh_id: 982875
INFO - ENV MKL_NUM_THREADS: None
INFO - ENV OMP_NUM_THREADS: None
INFO - ENV OPENBLAS_NUM_THREADS: None
INFO - NUMPY blas_info libraries: ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
INFO - NUMPY blas_opt_info libraries: ['cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
INFO - NUMPY lapack_info libraries: ['lapack', 'blas', 'lapack', 'blas']
INFO - NUMPY lapack_opt_info libraries: ['lapack', 'blas', 'lapack', 'blas', 'cblas', 'blas', 'cblas', 'blas', 'cblas', 'blas']
INFO - run single process simulation
INFO - Time to execute open_pipeline : 0.019 seconds (0.0 minutes)
INFO - preload_injectables
INFO - Time to execute preload_injectables : 0.019 seconds (0.0 minutes)
INFO - #run_model running step initialize_landuse
INFO - Reading CSV file data\land_use.csv
INFO - loaded land_use (25, 24)
INFO - initialize_landuse.annotate_tables - annotating land_use SPEC annotate_landuse
INFO - Network_LOS using skim_dict_factory: NumpyArraySkimFactory
INFO - allocate_skim_buffer shared False taz shape (826, 25, 25) total size: 2_065_000 (2.1 MB)
INFO - _read_skims_from_omx data\skims.omx
INFO - _read_skims_from_omx loaded 826 skims from data\skims.omx
INFO - writing skim cache taz (826, 25, 25) to output\cache\cached_taz.mmap
INFO - load_skims_to_buffer taz shape (826, 25, 25)
INFO - get_skim_data taz SkimData shape (826, 25, 25)
INFO - SkimDict init taz
INFO - SkimDict.build_3d_skim_block_offset_table registered 167 3d keys
INFO - #run_model running step initialize_households
INFO - Reading CSV file data\households.csv
INFO - full household list contains 5000 households
INFO - sampling 100 of 5000 households
INFO - loaded households (100, 7)
INFO - tracing household id 982875 in 100 households
INFO - Reading CSV file data\persons.csv
INFO - loaded persons (167, 7)
INFO - initialize_households.annotate_tables - annotating persons SPEC annotate_persons
INFO - initialize_households.annotate_tables - annotating households SPEC annotate_households
INFO - initialize_households.annotate_tables - annotating persons SPEC annotate_persons_after_hh
INFO - #run_model running step compute_accessibility
INFO - Running compute_accessibility with 25 orig zones 25 dest zones
INFO - compute_accessibility Running adaptive_chunked_choosers with 25 choosers
INFO - Running chunk 1 of 1 with 25 of 25 choosers
INFO - Running compute_accessibility with 25 orig zones 25 dest zones
INFO - compute_accessibility computed accessibilities (25, 10)
INFO - #run_model running step school_location
INFO - Running school_location.i1.sample.university with 17 persons
INFO - school_location.i1.sample.university.interaction_sample Running adaptive_chunked_choosers with 17 choosers
INFO - Running chunk 1 of 1 with 17 of 17 choosers
INFO - Running eval_interaction_utilities on 102 rows
INFO - Running school_location.i1.logsums.university with 44 rows
Traceback (most recent call last):
  File "l:\userdata\han\asim_v102\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "l:\userdata\han\asim_v102\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "L:\UserData\Han\asim_v102\Scripts\activitysim.exe\__main__.py", line 7, in <module>
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\cli\main.py", line 21, in main
    sys.exit(asim.execute())
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\cli\cli.py", line 27, in execute
    args.func(args)
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\cli\run.py", line 246, in run
    pipeline.run(models=config.setting('models'), resume_after=resume_after)
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\core\pipeline.py", line 624, in run
    run_model(model)
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\core\pipeline.py", line 483, in run_model
    orca.run([step_name])
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\core\orca.py", line 1853, in run
    step()
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\core\orca.py", line 772, in __call__
    return self._func(**kwargs)
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\abm\models\location_choice.py", line 920, in school_location
    iterate_location_choice(
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\abm\models\location_choice.py", line 774, in iterate_location_choice
    choices_df, save_sample_df = run_location_choice(
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\abm\models\location_choice.py", line 619, in run_location_choice
    run_location_logsums(
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\abm\models\location_choice.py", line 438, in run_location_logsums
    logsums = logsum.compute_logsums(
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\abm\models\util\logsums.py", line 76, in compute_logsums
    coefficients = simulate.get_segment_coefficients(logsum_settings, tour_purpose)
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\core\simulate.py", line 316, in get_segment_coefficients
    template_df = read_model_coefficient_template(model_settings)
  File "l:\userdata\han\asim_v102\lib\site-packages\activitysim\core\simulate.py", line 232, in read_model_coefficient_template
    template = template.where(~template.isnull(), template.index)
  File "l:\userdata\han\asim_v102\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "l:\userdata\han\asim_v102\lib\site-packages\pandas\core\frame.py", line 10733, in where
    return super().where(cond, other, inplace, axis, level, errors, try_cast)
  File "l:\userdata\han\asim_v102\lib\site-packages\pandas\core\generic.py", line 9023, in where
    return self._where(cond, other, inplace, axis, level, errors=errors)
  File "l:\userdata\han\asim_v102\lib\site-packages\pandas\core\generic.py", line 8834, in _where
    raise ValueError(
ValueError: other must be the same shape as self when an ndarray
Closing remaining open files:output\pipeline.h5...done
```

Best regards,
Han

**Comment by jpn--** [comment]
ActivitySim 1.0.1 is not compatible with pandas 1.3, see #449.  Try downgrading your install of pandas to 1.2:

```conda install "pandas=1.2"```

**Comment by stevenhz** [comment]
Thank you!
